{{- if .Values.ingress.enabled -}}
{{- $fullName := include "adventure-day-portal-api.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  annotations: 
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
                name: {{ $fullName }}
                port: 
                  number: {{ $svcPort }}
{{- end}}