apiVersion: v1
kind: Service
metadata:
  name: botsvc
  labels:
    name: botsvc    
spec:
  selector:
    name: gamebot    
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 50000      
      protocol: TCP