@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Context.puml

title System Context diagram for Azure GameDay

Person(hack_coach, "Hack Coaches", "SMEs helping the attendies")
Person(hack_team, "Hack Team", "Team consist of 3-4 hackers")

System(gameday_backend, "GameDay Backend", "Simulates customers and requests, scores the various game systems.")
System(game_system, "Game System", "Allows customers to play RPSLS against a automatic system. One per hack team.")

Rel(hack_coach, gameday_backend, "Owns")
Rel(hack_team, game_system, "Owns")

Rel(gameday_backend, game_system, "Challenges")
@enduml