/* 
 * Azure Game Day - RPSLS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using AzureGameDay.SDK.Client;
using AzureGameDay.SDK.Model;

namespace AzureGameDay.SDK.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMatchApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AzureGameDay.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="challengerId"></param>
        /// <returns>List&lt;Match&gt;</returns>
        List<Match> MatchGet (string challengerId);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AzureGameDay.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="challengerId"></param>
        /// <returns>ApiResponse of List&lt;Match&gt;</returns>
        ApiResponse<List<Match>> MatchGetWithHttpInfo (string challengerId);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AzureGameDay.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="matchRequest"></param>
        /// <returns>Match</returns>
        Match MatchPost (MatchRequest matchRequest);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AzureGameDay.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="matchRequest"></param>
        /// <returns>ApiResponse of Match</returns>
        ApiResponse<Match> MatchPostWithHttpInfo (MatchRequest matchRequest);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMatchApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AzureGameDay.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="challengerId"></param>
        /// <returns>Task of List&lt;Match&gt;</returns>
        System.Threading.Tasks.Task<List<Match>> MatchGetAsync (string challengerId);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AzureGameDay.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="challengerId"></param>
        /// <returns>Task of ApiResponse (List&lt;Match&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<Match>>> MatchGetAsyncWithHttpInfo (string challengerId);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AzureGameDay.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="matchRequest"></param>
        /// <returns>Task of Match</returns>
        System.Threading.Tasks.Task<Match> MatchPostAsync (MatchRequest matchRequest);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AzureGameDay.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="matchRequest"></param>
        /// <returns>Task of ApiResponse (Match)</returns>
        System.Threading.Tasks.Task<ApiResponse<Match>> MatchPostAsyncWithHttpInfo (MatchRequest matchRequest);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMatchApi : IMatchApiSync, IMatchApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class MatchApi : IMatchApi
    {
        private AzureGameDay.SDK.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="MatchApi"/> class.
        /// </summary>
        /// <returns></returns>
        public MatchApi() : this((string) null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MatchApi"/> class.
        /// </summary>
        /// <returns></returns>
        public MatchApi(String basePath)
        {
            this.Configuration = AzureGameDay.SDK.Client.Configuration.MergeConfigurations(
                AzureGameDay.SDK.Client.GlobalConfiguration.Instance,
                new AzureGameDay.SDK.Client.Configuration { BasePath = basePath }
            );
            this.Client = new AzureGameDay.SDK.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new AzureGameDay.SDK.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = AzureGameDay.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MatchApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public MatchApi(AzureGameDay.SDK.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = AzureGameDay.SDK.Client.Configuration.MergeConfigurations(
                AzureGameDay.SDK.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new AzureGameDay.SDK.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new AzureGameDay.SDK.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = AzureGameDay.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MatchApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public MatchApi(AzureGameDay.SDK.Client.ISynchronousClient client,AzureGameDay.SDK.Client.IAsynchronousClient asyncClient, AzureGameDay.SDK.Client.IReadableConfiguration configuration)
        {
            if(client == null) throw new ArgumentNullException("client");
            if(asyncClient == null) throw new ArgumentNullException("asyncClient");
            if(configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = AzureGameDay.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public AzureGameDay.SDK.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public AzureGameDay.SDK.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public AzureGameDay.SDK.Client.IReadableConfiguration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public AzureGameDay.SDK.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="AzureGameDay.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="challengerId"></param>
        /// <returns>List&lt;Match&gt;</returns>
        public List<Match> MatchGet (string challengerId)
        {
             AzureGameDay.SDK.Client.ApiResponse<List<Match>> localVarResponse = MatchGetWithHttpInfo(challengerId);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="AzureGameDay.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="challengerId"></param>
        /// <returns>ApiResponse of List&lt;Match&gt;</returns>
        public AzureGameDay.SDK.Client.ApiResponse< List<Match> > MatchGetWithHttpInfo (string challengerId)
        {
            // verify the required parameter 'challengerId' is set
            if (challengerId == null)
                throw new AzureGameDay.SDK.Client.ApiException(400, "Missing required parameter 'challengerId' when calling MatchApi->MatchGet");

            AzureGameDay.SDK.Client.RequestOptions localVarRequestOptions = new AzureGameDay.SDK.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = AzureGameDay.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = AzureGameDay.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (challengerId != null)
                localVarRequestOptions.PathParameters.Add("challengerId", AzureGameDay.SDK.Client.ClientUtils.ParameterToString(challengerId)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Get< List<Match> >("/Match/{challengerId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("MatchGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="AzureGameDay.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="challengerId"></param>
        /// <returns>Task of List&lt;Match&gt;</returns>
        public async System.Threading.Tasks.Task<List<Match>> MatchGetAsync (string challengerId)
        {
             AzureGameDay.SDK.Client.ApiResponse<List<Match>> localVarResponse = await MatchGetAsyncWithHttpInfo(challengerId);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="AzureGameDay.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="challengerId"></param>
        /// <returns>Task of ApiResponse (List&lt;Match&gt;)</returns>
        public async System.Threading.Tasks.Task<AzureGameDay.SDK.Client.ApiResponse<List<Match>>> MatchGetAsyncWithHttpInfo (string challengerId)
        {
            // verify the required parameter 'challengerId' is set
            if (challengerId == null)
                throw new AzureGameDay.SDK.Client.ApiException(400, "Missing required parameter 'challengerId' when calling MatchApi->MatchGet");


            AzureGameDay.SDK.Client.RequestOptions localVarRequestOptions = new AzureGameDay.SDK.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            if (challengerId != null)
                localVarRequestOptions.PathParameters.Add("challengerId", AzureGameDay.SDK.Client.ClientUtils.ParameterToString(challengerId)); // path parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<Match>>("/Match/{challengerId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("MatchGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="AzureGameDay.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="matchRequest"></param>
        /// <returns>Match</returns>
        public Match MatchPost (MatchRequest matchRequest)
        {
             AzureGameDay.SDK.Client.ApiResponse<Match> localVarResponse = MatchPostWithHttpInfo(matchRequest);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="AzureGameDay.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="matchRequest"></param>
        /// <returns>ApiResponse of Match</returns>
        public AzureGameDay.SDK.Client.ApiResponse< Match > MatchPostWithHttpInfo (MatchRequest matchRequest)
        {
            // verify the required parameter 'matchRequest' is set
            if (matchRequest == null)
                throw new AzureGameDay.SDK.Client.ApiException(400, "Missing required parameter 'matchRequest' when calling MatchApi->MatchPost");

            AzureGameDay.SDK.Client.RequestOptions localVarRequestOptions = new AzureGameDay.SDK.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = AzureGameDay.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = AzureGameDay.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = matchRequest;


            // make the HTTP request
            var localVarResponse = this.Client.Post< Match >("/Match", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("MatchPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="AzureGameDay.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="matchRequest"></param>
        /// <returns>Task of Match</returns>
        public async System.Threading.Tasks.Task<Match> MatchPostAsync (MatchRequest matchRequest)
        {
             AzureGameDay.SDK.Client.ApiResponse<Match> localVarResponse = await MatchPostAsyncWithHttpInfo(matchRequest);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="AzureGameDay.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="matchRequest"></param>
        /// <returns>Task of ApiResponse (Match)</returns>
        public async System.Threading.Tasks.Task<AzureGameDay.SDK.Client.ApiResponse<Match>> MatchPostAsyncWithHttpInfo (MatchRequest matchRequest)
        {
            // verify the required parameter 'matchRequest' is set
            if (matchRequest == null)
                throw new AzureGameDay.SDK.Client.ApiException(400, "Missing required parameter 'matchRequest' when calling MatchApi->MatchPost");


            AzureGameDay.SDK.Client.RequestOptions localVarRequestOptions = new AzureGameDay.SDK.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            localVarRequestOptions.Data = matchRequest;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Match>("/Match", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("MatchPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
