/* 
 * Azure Game Day - RPSLS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using AzureGameDay.SDK.Client;
using AzureGameDay.SDK.Api;
using AzureGameDay.SDK.Model;

namespace AzureGameDay.SDK.Test
{
    /// <summary>
    ///  Class for testing MatchSetupApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class MatchSetupApiTests : IDisposable
    {
        private MatchSetupApi instance;

        public MatchSetupApiTests()
        {
            instance = new MatchSetupApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MatchSetupApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' MatchSetupApi
            //Assert.IsType(typeof(MatchSetupApi), instance, "instance is a MatchSetupApi");
        }

        
        /// <summary>
        /// Test MatchSetupPost
        /// </summary>
        [Fact]
        public void MatchSetupPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //MatchSetupRequest matchSetupRequest = null;
            //var response = instance.MatchSetupPost(matchSetupRequest);
            //Assert.IsType<MatchSetup> (response, "response is MatchSetup");
        }
        
    }

}
