/* 
 * Azure Game Day - RPSLS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AzureGameDay.SDK.Api;
using AzureGameDay.SDK.Model;
using AzureGameDay.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AzureGameDay.SDK.Test
{
    /// <summary>
    ///  Class for testing Match
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MatchTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Match
        //private Match instance;

        public MatchTests()
        {
            // TODO uncomment below to create an instance of Match
            //instance = new Match();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Match
        /// </summary>
        [Fact]
        public void MatchInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Match
            //Assert.IsInstanceOfType<Match> (instance, "variable 'instance' is a Match");
        }


        /// <summary>
        /// Test the property 'MatchId'
        /// </summary>
        [Fact]
        public void MatchIdTest()
        {
            // TODO unit test for the property 'MatchId'
        }
        /// <summary>
        /// Test the property 'MatchSequenceNumber'
        /// </summary>
        [Fact]
        public void MatchSequenceNumberTest()
        {
            // TODO unit test for the property 'MatchSequenceNumber'
        }
        /// <summary>
        /// Test the property 'ChallengerId'
        /// </summary>
        [Fact]
        public void ChallengerIdTest()
        {
            // TODO unit test for the property 'ChallengerId'
        }
        /// <summary>
        /// Test the property 'WhenUtc'
        /// </summary>
        [Fact]
        public void WhenUtcTest()
        {
            // TODO unit test for the property 'WhenUtc'
        }
        /// <summary>
        /// Test the property 'ChallengerMove'
        /// </summary>
        [Fact]
        public void ChallengerMoveTest()
        {
            // TODO unit test for the property 'ChallengerMove'
        }
        /// <summary>
        /// Test the property 'OverlordMove'
        /// </summary>
        [Fact]
        public void OverlordMoveTest()
        {
            // TODO unit test for the property 'OverlordMove'
        }
        /// <summary>
        /// Test the property 'Outcome'
        /// </summary>
        [Fact]
        public void OutcomeTest()
        {
            // TODO unit test for the property 'Outcome'
        }

    }

}
