/* 
 * Azure Game Day - RPSLS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AzureGameDay.SDK.Api;
using AzureGameDay.SDK.Model;
using AzureGameDay.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AzureGameDay.SDK.Test
{
    /// <summary>
    ///  Class for testing MatchRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MatchRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MatchRequest
        //private MatchRequest instance;

        public MatchRequestTests()
        {
            // TODO uncomment below to create an instance of MatchRequest
            //instance = new MatchRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MatchRequest
        /// </summary>
        [Fact]
        public void MatchRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MatchRequest
            //Assert.IsInstanceOfType<MatchRequest> (instance, "variable 'instance' is a MatchRequest");
        }


        /// <summary>
        /// Test the property 'ChallengerId'
        /// </summary>
        [Fact]
        public void ChallengerIdTest()
        {
            // TODO unit test for the property 'ChallengerId'
        }
        /// <summary>
        /// Test the property 'MatchId'
        /// </summary>
        [Fact]
        public void MatchIdTest()
        {
            // TODO unit test for the property 'MatchId'
        }
        /// <summary>
        /// Test the property 'MatchSequenceNumber'
        /// </summary>
        [Fact]
        public void MatchSequenceNumberTest()
        {
            // TODO unit test for the property 'MatchSequenceNumber'
        }
        /// <summary>
        /// Test the property 'Move'
        /// </summary>
        [Fact]
        public void MoveTest()
        {
            // TODO unit test for the property 'Move'
        }

    }

}
