/* 
 * Azure Game Day - RPSLS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AzureGameDay.SDK.Api;
using AzureGameDay.SDK.Model;
using AzureGameDay.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AzureGameDay.SDK.Test
{
    /// <summary>
    ///  Class for testing Move
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MoveTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Move
        //private Move instance;

        public MoveTests()
        {
            // TODO uncomment below to create an instance of Move
            //instance = new Move();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Move
        /// </summary>
        [Fact]
        public void MoveInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Move
            //Assert.IsInstanceOfType<Move> (instance, "variable 'instance' is a Move");
        }



    }

}
