/* 
 * Azure Game Day - RPSLS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AzureGameDay.SDK.Api;
using AzureGameDay.SDK.Model;
using AzureGameDay.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AzureGameDay.SDK.Test
{
    /// <summary>
    ///  Class for testing Outcome
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OutcomeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Outcome
        //private Outcome instance;

        public OutcomeTests()
        {
            // TODO uncomment below to create an instance of Outcome
            //instance = new Outcome();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Outcome
        /// </summary>
        [Fact]
        public void OutcomeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Outcome
            //Assert.IsInstanceOfType<Outcome> (instance, "variable 'instance' is a Outcome");
        }



    }

}
