/* 
 * Azure Game Day - RPSLS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = AzureGameDay.SDK.Client.OpenAPIDateConverter;

namespace AzureGameDay.SDK.Model
{
    /// <summary>
    /// Match
    /// </summary>
    [DataContract]
    public partial class Match :  IEquatable<Match>, IValidatableObject
    {
        /// <summary>
        /// Gets or Sets ChallengerMove
        /// </summary>
        [DataMember(Name="challengerMove", EmitDefaultValue=false)]
        public Move? ChallengerMove { get; set; }
        /// <summary>
        /// Gets or Sets OverlordMove
        /// </summary>
        [DataMember(Name="overlordMove", EmitDefaultValue=false)]
        public Move? OverlordMove { get; set; }
        /// <summary>
        /// Gets or Sets Outcome
        /// </summary>
        [DataMember(Name="outcome", EmitDefaultValue=false)]
        public Outcome? Outcome { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Match" /> class.
        /// </summary>
        /// <param name="matchId">matchId.</param>
        /// <param name="matchSequenceNumber">matchSequenceNumber.</param>
        /// <param name="challengerId">challengerId.</param>
        /// <param name="whenUtc">whenUtc.</param>
        /// <param name="challengerMove">challengerMove.</param>
        /// <param name="overlordMove">overlordMove.</param>
        /// <param name="outcome">outcome.</param>
        public Match(string matchId = default(string), long matchSequenceNumber = default(long), string challengerId = default(string), DateTime whenUtc = default(DateTime), Move challengerMove = default(Move), Move overlordMove = default(Move), Outcome outcome = default(Outcome))
        {
            this.MatchId = matchId;
            this.MatchSequenceNumber = matchSequenceNumber;
            this.ChallengerId = challengerId;
            this.WhenUtc = whenUtc;
            this.ChallengerMove = challengerMove;
            this.OverlordMove = overlordMove;
            this.Outcome = outcome;
        }
        
        /// <summary>
        /// Gets or Sets MatchId
        /// </summary>
        [DataMember(Name="matchId", EmitDefaultValue=false)]
        public string MatchId { get; set; }

        /// <summary>
        /// Gets or Sets MatchSequenceNumber
        /// </summary>
        [DataMember(Name="matchSequenceNumber", EmitDefaultValue=false)]
        public long MatchSequenceNumber { get; set; }

        /// <summary>
        /// Gets or Sets ChallengerId
        /// </summary>
        [DataMember(Name="challengerId", EmitDefaultValue=false)]
        public string ChallengerId { get; set; }

        /// <summary>
        /// Gets or Sets WhenUtc
        /// </summary>
        [DataMember(Name="whenUtc", EmitDefaultValue=false)]
        public DateTime WhenUtc { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Match {\n");
            sb.Append("  MatchId: ").Append(MatchId).Append("\n");
            sb.Append("  MatchSequenceNumber: ").Append(MatchSequenceNumber).Append("\n");
            sb.Append("  ChallengerId: ").Append(ChallengerId).Append("\n");
            sb.Append("  WhenUtc: ").Append(WhenUtc).Append("\n");
            sb.Append("  ChallengerMove: ").Append(ChallengerMove).Append("\n");
            sb.Append("  OverlordMove: ").Append(OverlordMove).Append("\n");
            sb.Append("  Outcome: ").Append(Outcome).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Match);
        }

        /// <summary>
        /// Returns true if Match instances are equal
        /// </summary>
        /// <param name="input">Instance of Match to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Match input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.MatchId == input.MatchId ||
                    (this.MatchId != null &&
                    this.MatchId.Equals(input.MatchId))
                ) && 
                (
                    this.MatchSequenceNumber == input.MatchSequenceNumber ||
                    this.MatchSequenceNumber.Equals(input.MatchSequenceNumber)
                ) && 
                (
                    this.ChallengerId == input.ChallengerId ||
                    (this.ChallengerId != null &&
                    this.ChallengerId.Equals(input.ChallengerId))
                ) && 
                (
                    this.WhenUtc == input.WhenUtc ||
                    (this.WhenUtc != null &&
                    this.WhenUtc.Equals(input.WhenUtc))
                ) && 
                (
                    this.ChallengerMove == input.ChallengerMove ||
                    this.ChallengerMove.Equals(input.ChallengerMove)
                ) && 
                (
                    this.OverlordMove == input.OverlordMove ||
                    this.OverlordMove.Equals(input.OverlordMove)
                ) && 
                (
                    this.Outcome == input.Outcome ||
                    this.Outcome.Equals(input.Outcome)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.MatchId != null)
                    hashCode = hashCode * 59 + this.MatchId.GetHashCode();
                hashCode = hashCode * 59 + this.MatchSequenceNumber.GetHashCode();
                if (this.ChallengerId != null)
                    hashCode = hashCode * 59 + this.ChallengerId.GetHashCode();
                if (this.WhenUtc != null)
                    hashCode = hashCode * 59 + this.WhenUtc.GetHashCode();
                hashCode = hashCode * 59 + this.ChallengerMove.GetHashCode();
                hashCode = hashCode * 59 + this.OverlordMove.GetHashCode();
                hashCode = hashCode * 59 + this.Outcome.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
