/* 
 * Azure Game Day - RPSLS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = AzureGameDay.SDK.Client.OpenAPIDateConverter;

namespace AzureGameDay.SDK.Model
{
    /// <summary>
    /// Defines Move
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum Move
    {
        /// <summary>
        /// Enum Rock for value: Rock
        /// </summary>
        [EnumMember(Value = "Rock")]
        Rock = 1,

        /// <summary>
        /// Enum Paper for value: Paper
        /// </summary>
        [EnumMember(Value = "Paper")]
        Paper = 2,

        /// <summary>
        /// Enum Scissors for value: Scissors
        /// </summary>
        [EnumMember(Value = "Scissors")]
        Scissors = 3,

        /// <summary>
        /// Enum Lizard for value: Lizard
        /// </summary>
        [EnumMember(Value = "Lizard")]
        Lizard = 4,

        /// <summary>
        /// Enum Spock for value: Spock
        /// </summary>
        [EnumMember(Value = "Spock")]
        Spock = 5

    }

}
