/* 
 * Azure Game Day - RPSLS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = AzureGameDay.SDK.Client.OpenAPIDateConverter;

namespace AzureGameDay.SDK.Model
{
    /// <summary>
    /// Defines Outcome
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum Outcome
    {
        /// <summary>
        /// Enum ChallengerWins for value: ChallengerWins
        /// </summary>
        [EnumMember(Value = "ChallengerWins")]
        ChallengerWins = 1,

        /// <summary>
        /// Enum OverlordWins for value: OverlordWins
        /// </summary>
        [EnumMember(Value = "OverlordWins")]
        OverlordWins = 2,

        /// <summary>
        /// Enum Tie for value: Tie
        /// </summary>
        [EnumMember(Value = "Tie")]
        Tie = 3

    }

}
