name: Backend-IaC

on:
  workflow_dispatch:
    inputs:
      azureSecretName:
        description: 'Azure Secret Name containing the Service Principal Details'
        required: true
        default: 'AZURE_PROD'
      environmentName:
        description: 'The environment deployment name, e.g. dev, qa or prod'
        required: true
        default: 'prod'
      prefix:
        description: 'The deployment prefix used for all Azure artefacts.'
        required: true
        default: 'azure-adventure-day'
      location:
        description: 'The deployment location used for all Azure artefacts.'
        required: true
        default: 'northeurope'
      tag:
        description: 'The container image tag to apply'
        required: true
        default: '1'
      registryName:
        description: 'The Azure Container Registry name'
        required: true
        default: 'azureadventuredayprod6d0b53'
defaults:
  run:
    working-directory: AdventureDayBackend/
jobs:
  deploy:
    name: Deploy Helm Charts to Adventure Day Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets[github.event.inputs.azureSecretName] }}
      - name: Docker Build and Push All
        run: ./docker_build_and_push_all.ps1 -RegistryName  "${{ github.event.inputs.registryName }}" -Tag "${{ github.event.inputs.tag }}"
        shell: pwsh
        env:
          AZURE_CREDENTIALS: ${{ secrets[github.event.inputs.azureSecretName] }}
      - name: Run Helm Deploy
        working-directory: AdventureDayBackend/helm-charts
        run: ./helm_deploy_all.ps1 -RegistryName "${{ github.event.inputs.registryName }}" -Tag "${{ github.event.inputs.tag }}"
        shell: pwsh
        env:
          AZURE_CREDENTIALS: ${{ secrets[github.event.inputs.azureSecretName] }}
