name: Backend-Nightly-IaC-Destroy

on:
  schedule:
    # every night at 3am
    - cron:  '0 3 * * *'  

jobs:
  nightly-deploy-backend:
    name: Nightly test of deploying Adventure Day Backend to Azure
    runs-on: ubuntu-latest
    steps:
      - name: Invoke Backend-IaC-Destroy
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Backend-IaC-Destroy
          token: ${{ secrets.AZURE_ADVENTURE_DAY_NIGHTLY_PAT }}
          inputs: '{ "confirm": "1", "azureSecretName": "AZURE_RICARDO", "environmentName": "night" }'
