name: AdventureDay-Team-Build-Push-Game-Engine-To-AAD-GHCR

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - TeamGameHub/GameEngine/WebApi/**
      - .github/workflows/adventure-day-team-build-push-gameengine2.yml
   
defaults:
  run:
    working-directory: TeamGameHub/GameEngine/WebApi
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Docker build, tag and push     
      run: |        
  
        docker login -u ricardoniepel -p ${{ secrets.AZURE_ADVENTURE_DAY_COACH_PACKAGE_PAT }} ghcr.io
        docker build -t ghcr.io/azure-adventure-day/azure-adventure-day-coach/gamedayengine-web:latest .
        docker push ghcr.io/azure-adventure-day/azure-adventure-day-coach/gamedayengine-web:latest
