name: Build and Push GameBot

on:
  push:
    branches: [ master ]
    paths:
      - RPSLSGameHub/GameBot/**
      - .github/workflows/build-push-gamebot.yml
   
defaults:
  run:
    working-directory: RPSLSGameHub/GameBot
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Docker build, tag and push     
      run: |        
  
        docker login -u ricardoniepel -p ${{ secrets.AZURE_ADVENTURE_DAY_COACH_PACKAGE_PAT }} ghcr.io
        docker build -t ghcr.io/ricardoniepel/azure-adventure-day-coach/GameBot:latest .
        docker push ghcr.io/ricardoniepel/azure-adventure-day-coach/GameBot:latest
        
        
        
        
        
        
        
    
